name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: node:16.16.0

    steps:
    - uses: actions/checkout@v3
    - name: install
      run:  npm install
    - name: runSite
      run: npm run site
    - name: cpoyFIle
      run: cp ./Dockerfile ./site/dist
    - name: copyNginx
      run: cp  ./nginx.conf ./site/dist
    - name: changePath
      run: cd ./site/dist 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pf-ui-vue:$(date +%s)
